// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9LTvOEm5TLAa5TuBpTC0XvKEHv1fe-ew',
    appId: '1:852681175943:web:a326053579c0e103bfd922',
    messagingSenderId: '852681175943',
    projectId: 'flutter-pro-firebase-c5a0e',
    authDomain: 'flutter-pro-firebase-c5a0e.firebaseapp.com',
    storageBucket: 'flutter-pro-firebase-c5a0e.firebasestorage.app',
    measurementId: 'G-SNPR1SNMZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCefkrkLNHnE4hfXxWh8by9NNqWuGxhWVY',
    appId: '1:852681175943:android:a1093d674a510b19bfd922',
    messagingSenderId: '852681175943',
    projectId: 'flutter-pro-firebase-c5a0e',
    storageBucket: 'flutter-pro-firebase-c5a0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUCdu07ET6_134__tyeQhEojiqkNJmfCY',
    appId: '1:852681175943:ios:96ef82106471a531bfd922',
    messagingSenderId: '852681175943',
    projectId: 'flutter-pro-firebase-c5a0e',
    storageBucket: 'flutter-pro-firebase-c5a0e.firebasestorage.app',
    iosBundleId: 'com.example.practiceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUCdu07ET6_134__tyeQhEojiqkNJmfCY',
    appId: '1:852681175943:ios:96ef82106471a531bfd922',
    messagingSenderId: '852681175943',
    projectId: 'flutter-pro-firebase-c5a0e',
    storageBucket: 'flutter-pro-firebase-c5a0e.firebasestorage.app',
    iosBundleId: 'com.example.practiceFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9LTvOEm5TLAa5TuBpTC0XvKEHv1fe-ew',
    appId: '1:852681175943:web:e2eafca81f84f742bfd922',
    messagingSenderId: '852681175943',
    projectId: 'flutter-pro-firebase-c5a0e',
    authDomain: 'flutter-pro-firebase-c5a0e.firebaseapp.com',
    storageBucket: 'flutter-pro-firebase-c5a0e.firebasestorage.app',
    measurementId: 'G-EBC2LMCS60',
  );
}
